### ISSUE TITLE
We should add STOPSIGNAL to dockerfile to make httpd die gracefully 

### ISSUE THREAD

**Issue by mfojtik** [sclorg/s2i-perl-container#83] opened 2016-05-06 09:25 UTC
See: https://docs.docker.com/engine/reference/builder/#stopsignal

The httpd use "SIGWINCH" signal to shutdown "gracefully". We should send that (systemd does it as well).

**Comment by ppisar** [comment] 2016-05-06 11:48
That means the "docker stop" will wait for finishing serving all opened
requests (and send SIGKILL after 10 seconds by default). I'd like to see
agreement among other httpd-running images to provide uniform behaviour.

I'm not against it if we talk about application images. But I have bad feeling
again. Those who use the image for non-s2i purposes will need to override yet
another Dockerfile instruction to restore the termination signal. SIGWINCH is
a non-terminating signal, so these users will obtain image that will terminate
always after 10 seconds.

**Comment by mfojtik** [comment] 2016-05-06 12:34
@ppisar openshift/kube will send SIGKILL after some period of time... I believe this signal is sent as first, allowing the container to die "nicely" ;-)

@bparees FYI

**Comment by bparees** [comment] 2016-05-06 12:57
@mfojtik what signal is sent by default on a docker stop (before the 10s grace period expires)?  and how does httpd handle that signal?

**Comment by ppisar** [comment] 2016-05-06 12:58
On Fri, May 06, 2016 at 05:34:02AM -0700, Michal Fojtik wrote:
> send SIGKILL after some period of time...
>
And that would be the regression. Now "docker stop" sends SIGTERM which causes
any well-behaved software to exit. After the change you will get 10-second
pause because the process will recieve SIGWINCH instead.

This is irelevant for an s2i aplication built from the image because it
executes httpd thet also terminates on SIGWINCH. But any other program will
ignore it because this is the default SIGWINCH action.

If I'm s2i application user I'm perfectly fine with the change. But If I'm
non-s2i application user, I'm not fine with it.

**Comment by bparees** [comment] 2016-05-06 15:28
i'm inclined to agree with @ppisar

**Comment by hhorak** [comment] 2017-03-28 07:20
There is not a clear consensus about the change, and since I'm not aware of any issues with the current behavior, I'm more inclined to close this issue.

**Closed** 2017-03-28 11:46 UTC
Labels: enhancement
