### ISSUE TITLE
How to hot deploy with mod_fcgid?

### ISSUE THREAD

**Issue by yselkowitz** [sclorg/s2i-perl-container#206] opened 2021-04-14 22:51 UTC
image_ecosystem tests hot deploy for perl in a way that appears dependent on mod_perl:

https://github.com/openshift/origin/blob/master/test/extended/image_ecosystem/s2i_perl.go#L89-L120

Using this as a sample app:

https://github.com/openshift/origin/tree/master/test/extended/testdata/image_ecosystem/perl-hotdeploy

I am currently trying to port this test to ubi8/perl-530 (which is of course mod_fcgid-based) but I'm not sure how to do so.  Any pointers?

**Comment by michal-josef-spacek** [comment] 2021-09-15 09:23
I could help with it.

**Comment by phracek** [comment] 2021-09-29 10:35
@yselkowitz Can you please provide us more information about hot-deploy? Any documentation? How it should work in a container? The issue is related only to RHEL7 images, right? And even, how we can set up and test it?

Thank you 

CC: @michal-josef-spacek @pkubatrh  @hhorak

**Comment by yselkowitz** [comment] 2021-09-30 20:30
The links above show the enablement of hot config and the application being tested.  In short, it is relying on setting `PERL_APACHE2_RELOAD` to control this, which means it's relying on Apache2::Reload with mod_perl.  UBI 8 uses mod_fcgid, so that won't do anything.  I think the solution might be [plackup -r](https://metacpan.org/pod/Plack::Loader::Restarter) but does that require changing the s2i glue to conditionally pass `-r` to plackup based on a new environment variable?  Or is there a better way to handle this?

**Comment by phracek** [comment] 2021-10-04 12:33
> The links above show the enablement of hot config and the application being tested. In short, it is relying on setting `PERL_APACHE2_RELOAD` to control this, which means it's relying on Apache2::Reload with mod_perl. UBI 8 uses mod_fcgid, so that won't do anything. I think the solution might be [plackup -r](https://metacpan.org/pod/Plack::Loader::Restarter) but does that require changing the s2i glue to conditionally pass `-r` to plackup based on a new environment variable? Or is there a better way to handle this?

@michal-josef-spacek Does it help you @yselkowitz comment to implement it and test it?

**Comment by phracek** [comment] 2021-11-15 11:28
I have filed a Bugzilla for this issue. https://bugzilla.redhat.com/show_bug.cgi?id=2023278

**Comment by michal-josef-spacek** [comment] 2021-11-15 14:56
PSGI application for hot-deploy PR: https://github.com/openshift/origin/pull/26607

**Comment by michal-josef-spacek** [comment] 2021-11-15 15:32
btw: On old containers this PSGI application hasn't possiblity of this kind of reload.

**Comment by michal-josef-spacek** [comment] 2021-11-16 10:37
Support for this in s2i-perl container: https://github.com/sclorg/s2i-perl-container/pull/221

**Comment by michal-josef-spacek** [comment] 2021-11-18 18:06
@yselkowitz @phracek I added tests for PSGI_RELOAD functionality

**Comment by michal-josef-spacek** [comment] 2022-05-19 16:48
Rebase PR again: https://github.com/sclorg/s2i-perl-container/pull/236

**Comment by phracek** [comment] 2022-06-02 10:07
This is fixed by https://github.com/sclorg/s2i-perl-container/pull/236

**Closed by phracek** 2022-06-02 10:07 UTC

**Comment by michal-josef-spacek** [comment] 2022-06-02 10:08
@yselkowitz If you need some other help from me, ping me, please.
